baseURL = 'http://pep.codes/'
languageCode = 'en-us'
title = 'Pep Codes'
theme        = "hello-friend-ng"

paginate  = 10
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License." # This message is only used by the RSS template.


[author]
  name = "Pep Turró Mauri"

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "A work in progress home page"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = false

  # Metadata mostly used in document's head
  description = "Pep's homepage"
  keywords = "homepage, blog"
  images = [""]

  [params.footer]
    trademark = true
    rss = true
    copyright = true
    author = true

    topText = []
    bottomText = [
      "Powered by <a href=\"https://www.gnu.org/software/emacs/\">Emacs</a> &amp; <a href=\"https://gohugo.io\">Hugo</a>",
      # "Made with &#10084; by <a href=\"https://github.com/codificat\"><code>codificat</code></a>"
      "<a href=\"https://github.com/rhazdon/hugo-theme-hello-friend-ng\">Hello Friend NG</a> theme"
    ]

  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/codificat"

  [[params.social]]
    name = "mastodon"
    url = "https://mastodont.cat/@codificat"

  [[params.social]]
    name = "github"
    url  = "https://github.com/codificat"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/peptm"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Pep Codes"
    subtitle = "A work in progress home page"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">CC BY-SA 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoMark = ">"
      logoText = "pep.codes"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

[markup.goldmark.renderer]
  unsafe = true
